name: typecheck

on:
  push:

jobs:
  tsc:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm tsc